#!/usr/bin/env bash
pushd "$(pwd)"
rm -rf build
mkdir build
cd build

echo "Preparing cmake"
cmake ..
result=$?
if [ $result -ne 0 ]; then
    echo "Something went wrong with cmake"
    exit 1
fi
cmake --build .
result=$?
if [ $result -ne 0 ]; then
    echo "Something went wrong with code build"
    exit 1
fi
ctest --output-on-failure
result=$?
if [ $result -ne 0 ]; then
    echo "Something went wrong with tests"
    exit 1
fi
cd ..
./scripts/test.sh
result=$?
if [ $result -ne 0 ]; then
    echo "Something went wrong with code generation"
    exit 1
fi
popd
