name: build
on: push

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential flex bison cmake -y
          sudo wget https://apt.llvm.org/llvm.sh
          sudo chmod +x llvm.sh
          sudo ./llvm.sh 14 all
          sudo rm llvm.sh
          sudo update-alternatives --install \
            /usr/bin/llvm-config       llvm-config      /usr/bin/llvm-config-14  200 
          sudo apt-get remove llvm-12 llvm-10 -y
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - name: Unit Test
        run: |
          cd build
          ctest --output-on-failure
      - name: Test
        run: ./scripts/test.sh
  mac:
    name: mac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          brew update
          brew install bison flex llvm
          echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/flex/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - name: Unit Test
        run: |
          cd build
          ctest --output-on-failure
      - name: Test
        run: ./scripts/test.sh
