name: build
on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: apt-get update && apt-get install build-essential flex bison clang -y
      - run: make
      - run: ./bin/ni < examples/test.ni
