name: build
on: push

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    env:
      LLVM_VERSION: 13
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install build-essential flex bison -y
      - run: make
      - run: make test
  mac:
    name: mac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          brew install bison flex
          echo "/usr/local/opt/flex/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/bison/bin" >> $GITHUB_PAT
      - run: make
      - run: make test
