name: build
on: push

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential flex bison cmake -y
      - name: Install LLVM
        run: |
          curl -O https://apt.llvm.org/llvm.sh
          cat llvm.sh | sed 's|apt-get install -y $PKG|apt-get install -o Dpkg::Options::="--force-overwrite" -y $PKG|' > llvm2.sh
          mv llvm2.sh llvm.sh
          chmod +x llvm.sh
          sudo bash ./llvm.sh 15 all
          rm llvm.sh
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - name: Unit Test
        run: |
          cd build
          ctest --output-on-failure
  mac:
    name: mac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          brew update
          brew install bison flex llvm@15
          echo "$(brew --prefix llvm@15)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix flex)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - name: Unit Test
        run: |
          cd build
          ctest --output-on-failure
