name: coverage
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential flex bison cmake lcov -y
          
      - name: Install LLVM
        run: |
          curl -O https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo bash ./llvm.sh 21 all
          rm llvm.sh
          
      - name: Configure with coverage
        run: |
          mkdir build
          cd build
          cmake .. -DENABLE_COVERAGE=ON
          
      - name: Build
        run: |
          cd build
          cmake --build .
          
      - name: Run tests with coverage
        run: |
          cd build
          ctest --output-on-failure
          
      - name: Generate coverage info
        run: |
          cd build
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/build/*' '*/test/*' '*/_deps/*' '*/scanner.c' '*/parser.tab.c' --output-file coverage.info.cleaned
          lcov --list coverage.info.cleaned
          
      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/coverage.info.cleaned
          flag-name: ubuntu-coverage
          parallel: false
